### ISSUE TITLE
Certain datafiles not copying over into build/output

### ISSUE THREAD

**Issue by objShaggy** [thennothinghappened/GMEdit-Constructor#22]
When compiling the compiler does not copy over the datafiles mod-music.bank and mod-sfx.bank.
I hate it.

**Comment by thennothinghappened** [comment]
I've not heard of any issues with included files previously and I use them in a number of my own games without issue, so going to need some more information here — please attach a compile log, there's not much for me to go off of without one.

For narrowing it down preliminary, I'll need to know two things:

1. Can you reproduce this issue in a new project with just some data files? (if not, this could be a YYP issue, not on Constructor's end, in which case you'll want to run your project through ProjectTool to clean up possible errors. If you're on a runtime >=2024.2, and these assets were added via GMEdit, there is an extremely high chance that this is the cause of your issue. GMEdit still isn't quite up to scratch since YYv2 came out, since the new format is extremely picky.)

2. If you enable the central build directory, does the issue persist? (checking for permissions issues, which have happened plenty of times here.)

**Comment by objShaggy** [comment]
Turns out it was a YYP issue and not fault of the constructor, thanks for the help!
