### ISSUE TITLE
Kill instances via F6

### ISSUE THREAD

**Issue by spacebake** [thennothinghappened/GMEdit-Constructor#25]
I seem to only be able to kill current instances of the game window by closing them manually.
Would be nice to be able to kill them (or cancel a compile) via F6 like in builder.
Maybe I'm missing something?

**Comment by thennothinghappened** [comment]
Ideally the Stop button and re-hitting F5 should do this but due to #23, which I encountered a completely blocking issue on as Igor does not respond properly to being run in a new process group for some reason and prints an error and refuses to run - making it currently impossible to close the child processes that Igor spawns - this behaviour is not implemented.

**Comment by thennothinghappened** [comment]
I've fixed #23 in the latest update, it was... not fun, thanks to MacOS. I've given some details in Constructor's GM Kitchen thread about how I'm planning to tackle this, which would also make room for #21.

**Comment by spacebake** [comment]
hot damn, that was fast
